export const category = [
  { key: "ainu", text: "Ainu", value: "ainu" },
  { key: "albanian", text: "Albanian", value: "albanian" },
  { key: "argentine", text: "Argentine", value: "argentine" },
  { key: "andhra", text: "Andhra", value: "andhra" },
  { key: "anglo-indian", text: "Anglo-Indian", value: "anglo-indian" },
  { key: "arab", text: "Arab", value: "arab" },
  { key: "armenian", text: "Armenian", value: "armenian" },
  { key: "assyrian", text: "Assyrian", value: "assyrian" },
  { key: "awadhi", text: "Awadhi", value: "awadhi" },
  { key: "azerbaijani", text: "Azerbaijani", value: "azerbaijani" },
  { key: "balochi", text: "Balochi", value: "balochi" },
  { key: "belarusian", text: "Belarusian", value: "belarusian" },
  { key: "bangladeshi", text: "Bangladeshi", value: "bangladeshi" },
  { key: "bengali", text: "Bengali", value: "bengali" },
  { key: "berber", text: "Berber", value: "berber" },
  { key: "brazilian", text: "Brazilian", value: "brazilian" },
  { key: "buddhist", text: "Buddhist", value: "buddhist" },
  { key: "bulgarian", text: "Bulgarian", value: "bulgarian" },
  { key: "cajun", text: "Cajun", value: "cajun" },
  { key: "cantonese", text: "Cantonese", value: "cantonese" },
  { key: "caribbean", text: "Caribbean", value: "caribbean" },
  { key: "chechen", text: "Chechen", value: "chechen" },
  { key: "chinese", text: "Chinese", value: "chinese" },
  {
    key: "chinese-islamic",
    text: "Chinese Islamic",
    value: "chinese-islamic",
  },
  { key: "circassian", text: "Circassian", value: "circassian" },
  {
    key: "crimean-tatar",
    text: "Crimean Tatar",
    value: "crimean-tatar",
  },
  { key: "cypriot", text: "Cypriot", value: "cypriot" },
  { key: "danish", text: "Danish", value: "danish" },
  { key: "english", text: "English", value: "english" },
  { key: "estonian", text: "Estonian", value: "estonian" },
  { key: "french", text: "French", value: "french" },
  { key: "filipino", text: "Filipino", value: "filipino" },
  { key: "georgian", text: "Georgian", value: "georgian" },
  { key: "german", text: "German", value: "german" },
  { key: "goan", text: "Goan", value: "goan" },
  { key: "greek", text: "Greek", value: "greek" },
  { key: "gujarati", text: "Gujarati", value: "gujarati" },
  { key: "Hyderabad", text: "Hyderabad", value: "hyderabad" },
  { key: "cuisine", text: "Indian ", value: "" },
  {
    key: "indian-chinese",
    text: "Indian Chinese",
    value: "indian-chinese",
  },
  {
    key: "indian-singaporean",
    text: "Indian Singaporean ",
    value: "indian-singaporean",
  },
  { key: "indonesian", text: "Indonesian", value: "indonesian" },
  { key: "inuit", text: "Inuit", value: "inuit" },
  { key: "irish", text: "Irish", value: "irish" },
  {
    key: "italian-american",
    text: "Italian American",
    value: "italian-american",
  },
  { key: "italian", text: "Italian ", value: "italian" },
  { key: "jamaican", text: "Jamaican", value: "jamaican" },
  { key: "japanese", text: "Japanese", value: "japanese" },
  { key: "jewish", text: "Jewish", value: "jewish" },
  { key: "karnataka", text: "Karnataka", value: "karnataka" },
  { key: "kazakh", text: "Kazakh", value: "kazakh" },
  { key: "keralite", text: "Keralite", value: "keralite" },
  { key: "korean", text: "Korean", value: "korean" },
  { key: "kurdish", text: "Kurdish", value: "kurdish" },
  { key: "laotian", text: "Laotian", value: "Laotian" },
  { key: "lebanese", text: "Lebanese", value: "lebanese" },
  { key: "latvian", text: "Latvian", value: "latvian" },
  { key: "lithuanian", text: "Lithuanian", value: "lithuanian" },
  {
    key: "louisana-Creole",
    text: "Louisiana Creole",
    value: "louisana-creole",
  },
  {
    key: "maharashtrian",
    text: "Maharashtrian",
    value: "maharashtrian",
  },
  { key: "mangalorean", text: "Mangalorean", value: "mangalorean" },
  { key: "malay", text: "Malay", value: "malay" },
  {
    key: "malaysian-chinese",
    text: "Malaysian Chinese ",
    value: "malaysian-chinese",
  },
  {
    key: "malaysian-indian",
    text: "Malaysian Indian ",
    value: "malaysian-indian",
  },
  {
    key: "mediterranean",
    text: "Mediterranean ",
    value: "mediterranean",
  },
  { key: "mexican", text: "Mexican", value: "mexican" },
  { key: "mordovian", text: "Mordovian", value: "mordovian" },
  { key: "mughal", text: "Mughal", value: "mughal" },
  {
    key: "native-american",
    text: "Native American",
    value: "native-american",
  },
  { key: "nepalese", text: "Nepalese", value: "nepalese" },
  { key: "new-mexican", text: "New Mexican", value: "new-mexican" },
  { key: "odia", text: "Odia", value: "odia" },
  { key: "parsi", text: "Parsi", value: "parsi" },
  { key: "pashtun", text: "Pashtun", value: "pashtun" },
  { key: "polish", text: "Polish", value: "polish" },
  {
    key: "pennsylvania-dutch",
    text: "Pennsylvania Dutch",
    value: "pennsylvania-dutch",
  },
  { key: "pakistani", text: "Pakistani", value: "pakistani" },
  { key: "peranakan", text: "Peranakan", value: "peranakan" },
  { key: "persian", text: "Persian", value: "persian" },
  { key: "peruvian", text: "Peruvian", value: "peruvian" },
  { key: "portuguese", text: "Portuguese", value: "portuguese" },
  { key: "punjabi", text: "Punjabi", value: "punjabi" },
  { key: "rajasthani", text: "Rajasthani", value: "rajasthani" },
  { key: "romanian", text: "Romanian", value: "romanian" },
  { key: "russian", text: "Russian", value: "russian" },
  { key: "sami", text: "Sami", value: "sami" },
  { key: "serbian", text: "Serbian", value: "serbian" },
  { key: "sindhi", text: "Sindhi", value: "sindhi" },
  { key: "slovak", text: "Slovak", value: "slovak" },
  { key: "slovenian", text: "Slovenian", value: "slovenian" },
  { key: "somali", text: "Somali", value: "somali" },
  { key: "south-indian", text: "South Indian", value: "south-indian" },
  { key: "soviet", text: "Soviet", value: "soviet" },
  { key: "spanish", text: "Spanish", value: "spanish" },
  { key: "sri-lankan", text: "Sri Lankan", value: "sri-lankan" },
  { key: "taiwanese", text: "Taiwanese", value: "taiwanese" },
  { key: "tatar", text: "Tatar", value: "tatar" },
  { key: "thai", text: "Thai", value: "thai" },
  { key: "turkish", text: "Turkish", value: "turkish" },
  { key: "tamil", text: "Tamil", value: "tamil" },
  { key: "udupi", text: "Udupi", value: "udupi" },
  { key: "ukrainian", text: "Ukrainian", value: "ukrainian" },
  { key: "vietnamese", text: "Vietnamese", value: "vietnamese" },
  { key: "yamal", text: "Yamal", value: "yamal" },
  { key: "zambian", text: "Zambian", value: "zambian" },
  { key: "zanzibari", text: "Zanzibari", value: "zanzibari" },
];
